"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/AuthProvider";
export function AdminLogin() { const auth = useAuth(); const router = useRouter(); const [step, setStep] = useState<"phone" | "otp">("phone"); const [phone, setPhone] = useState(""); const [otp, setOtp] = useState(""); const [devOtp, setDevOtp] = useState<string | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); useEffect(() => { if (auth.user?.roles.includes("admin")) router.replace("/bookings"); }, [auth.user, router]);
  async function send(event: FormEvent) { event.preventDefault(); setError(""); setDevOtp(null); if (!/^\d{10}$/.test(phone.replace(/\D/g, ""))) { setError("Enter a 10-digit Indian mobile number."); return; } setBusy(true); try { await auth.requestOtp(phone); setStep("otp"); if (process.env.NODE_ENV !== "production") setDevOtp(await auth.peekDevOtp(phone)); } catch (e) { setError(e instanceof Error ? e.message : "Could not send OTP."); } finally { setBusy(false); } }
  async function verify(event: FormEvent) { event.preventDefault(); setError(""); setBusy(true); try { await auth.verifyOtp(phone, otp); } catch (e) { setError(e instanceof Error ? e.message : "Could not verify OTP."); } finally { setBusy(false); } }
  if (auth.ready && auth.user && !auth.user.roles.includes("admin")) return <div role="alert"><h1 className="text-2xl font-semibold">Access denied</h1><p className="mt-2 text-slate-400">This phone is authenticated, but its persisted account role is not admin.</p><button className="mt-5 rounded bg-slate-800 px-4 py-2" onClick={() => void auth.logout()}>Sign out</button></div>;
  return <form onSubmit={step === "phone" ? send : verify} className="rounded-xl border border-slate-800 bg-slate-900 p-6"><p className="text-xs font-semibold uppercase tracking-widest text-sky-400">Internal access</p><h1 className="mt-2 text-2xl font-semibold">Booking operations sign in</h1><p className="mt-2 text-sm text-slate-400">Use the phone number attached to your admin account. Roles cannot be selected during login.</p>{step === "phone" ? <label className="mt-6 block text-sm">Mobile number<input aria-label="Mobile number" className="mt-2 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2" inputMode="numeric" value={phone} onChange={e => setPhone(e.target.value)} /></label> : <label className="mt-6 block text-sm">One-time code<input aria-label="One-time code" className="mt-2 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2" inputMode="numeric" value={otp} onChange={e => setOtp(e.target.value)} /></label>}{process.env.NODE_ENV !== "production" && devOtp ? <p className="mt-3 text-xs text-slate-400">Development code: <span className="font-mono text-sky-300">{devOtp}</span></p> : null}{error ? <p role="alert" className="mt-3 text-sm text-red-400">{error}</p> : null}<button type="submit" disabled={busy} className="mt-5 w-full rounded bg-sky-500 px-4 py-2 font-semibold text-slate-950 disabled:opacity-60">{busy ? "Please wait…" : step === "phone" ? "Send OTP" : "Verify OTP"}</button></form>;
}
