"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useAuth } from "@/components/AuthProvider";
import { localDateTime, problem, type AdminBookingPage } from "@/lib/admin-bookings";
const filters = ["pending", "accepted", "rejected", "confirmed", "cancelled"];
export function BookingQueue() { const auth = useAuth(); const [status, setStatus] = useState("pending"); const [pageNumber, setPageNumber] = useState(1); const [data, setData] = useState<AdminBookingPage | null>(null); const [error, setError] = useState("");
  const load = useCallback(async () => { setData(null); setError(""); try { const response = await auth.authenticatedFetch(`/api/admin/bookings?status=${status}&page=${pageNumber}&pageSize=25`); if (!response.ok) throw new Error(await problem(response)); setData(await response.json() as AdminBookingPage); } catch (e) { setError(e instanceof Error ? e.message : "Could not load booking queue."); } }, [auth, pageNumber, status]); useEffect(() => { void load(); }, [load]);
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-sky-400">Operations</p><h1 className="mt-2 text-3xl font-semibold">Booking queue</h1></div><p className="text-sm text-slate-400">Pending requests are ordered by pickup time, request time, then ID.</p></div><div aria-label="Booking status filters" className="mt-7 flex flex-wrap gap-2">{filters.map(item => <button key={item} aria-pressed={status === item} className={`rounded border px-3 py-2 text-sm font-medium capitalize ${status === item ? "border-sky-400 bg-sky-500/10 text-sky-300" : "border-slate-700 text-slate-300"}`} onClick={() => { setStatus(item); setPageNumber(1); }}>{item}</button>)}</div>
    {!data && !error ? <p role="status" className="mt-8 text-slate-400">Loading booking queue…</p> : null}{error ? <div role="alert" className="mt-8 rounded border border-red-900 bg-red-950/40 p-4 text-red-200"><p>{error}</p><button className="mt-2 underline" onClick={() => void load()}>Try again</button></div> : null}{data?.items.length === 0 ? <div className="mt-8 rounded border border-slate-800 bg-slate-900 p-8 text-center text-slate-400">No {status} bookings.</div> : null}
    {data && data.items.length > 0 ? <div className="mt-8 overflow-x-auto rounded border border-slate-800"><table className="min-w-full text-left text-sm"><thead className="bg-slate-900 text-xs uppercase tracking-wide text-slate-400"><tr>{["Booking", "Status", "Pickup", "Drop", "Pickup time", "Vehicle", "Requested"].map(x => <th className="px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{data.items.map(item => <tr className="border-t border-slate-800 bg-slate-950 hover:bg-slate-900/60" key={item.id}><td className="px-4 py-4 font-semibold text-sky-300"><Link href={`/bookings/${item.id}`}>{item.bookingNumber}</Link></td><td className="px-4 py-4">{item.statusLabel}</td><td className="max-w-60 px-4 py-4">{item.pickup}</td><td className="max-w-60 px-4 py-4">{item.drop}</td><td className="whitespace-nowrap px-4 py-4">{localDateTime(item.pickupAt, item.pickupTimezone)}</td><td className="px-4 py-4">{item.vehicleTypeName}</td><td className="whitespace-nowrap px-4 py-4 text-slate-400">{localDateTime(item.createdAt, "Asia/Kolkata")}</td></tr>)}</tbody></table></div> : null}
    {data && data.totalPages > 1 ? <div className="mt-5 flex gap-4"><button disabled={pageNumber <= 1} onClick={() => setPageNumber(x => x - 1)}>Previous</button><span>Page {data.page} of {data.totalPages}</span><button disabled={pageNumber >= data.totalPages} onClick={() => setPageNumber(x => x + 1)}>Next</button></div> : null}</div>;
}
