"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useAuth } from "@/components/AuthProvider";
import { localDateTime, problem, type AdminBookingDetails } from "@/lib/admin-bookings";
import { AssignmentPanel } from "@/components/AssignmentPanel";
export function BookingDetails({ id }: { id: string }) { const auth = useAuth(); const [booking, setBooking] = useState<AdminBookingDetails | null>(null); const [reason, setReason] = useState(""); const [busy, setBusy] = useState<"accept" | "reject" | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { const response = await auth.authenticatedFetch(`/api/admin/bookings/${id}`); if (!response.ok) throw new Error(await problem(response)); setBooking(await response.json() as AdminBookingDetails); }, [auth, id]); useEffect(() => { void load().catch(e => setError(e instanceof Error ? e.message : "Could not load booking.")); }, [load]);
  async function transition(action: "accept" | "reject") { if (action === "reject" && reason.trim().length < 3) { setError("Enter a rejection reason of at least 3 characters."); return; } if (!window.confirm(action === "accept" ? "Accept this request? This does not assign a driver or vehicle." : "Reject this request?")) return; setBusy(action); setError(""); setNotice(""); try { const response = await auth.authenticatedFetch(`/api/admin/bookings/${id}/${action}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: action === "reject" ? JSON.stringify({ reason: reason.trim() }) : undefined }); if (!response.ok) throw new Error(response.status === 409 ? "This booking changed. Refresh and review its current status." : await problem(response)); setBooking(await response.json() as AdminBookingDetails); setReason(""); setNotice(action === "accept" ? "Booking request accepted." : "Booking request rejected."); } catch (e) { setError(e instanceof Error ? e.message : "Could not update booking."); } finally { setBusy(null); } }
  if (!booking && !error) return <p role="status" className="text-slate-400">Loading booking details…</p>; if (!booking) return <p role="alert" className="text-red-300">{error}</p>;
  const fields = [["Customer", booking.contactName], ["Mobile", booking.contactMobile], ["Email", booking.contactEmail ?? "—"], ["Service", booking.serviceType], ["Journey", booking.airportJourneyType ?? "One way"], ["Vehicle requested", booking.vehicleTypeName], ["Pickup", booking.pickup], ["Drop", booking.drop], ["Pickup time", localDateTime(booking.pickupAt, booking.pickupTimezone)], ["Return time", booking.returnAt ? localDateTime(booking.returnAt, booking.pickupTimezone) : "—"], ["Requested", localDateTime(booking.createdAt, "Asia/Kolkata")], ["Customer notes", booking.customerNotes ?? "—"]];
  return <div><Link href="/bookings" className="text-sm font-semibold text-sky-400">← Booking queue</Link><div className="mt-5"><p className="text-xs uppercase tracking-widest text-sky-400">{booking.statusLabel}</p><h1 className="mt-2 text-3xl font-semibold">{booking.bookingNumber}</h1></div>{notice ? <p role="status" className="mt-5 rounded border border-emerald-800 bg-emerald-950/40 p-3 text-emerald-200">{notice}</p> : null}{error ? <p role="alert" className="mt-5 rounded border border-red-900 bg-red-950/40 p-3 text-red-200">{error}</p> : null}<dl className="mt-8 grid gap-5 rounded border border-slate-800 bg-slate-900 p-6 sm:grid-cols-2">{fields.map(([label, value]) => <div key={label}><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-slate-100">{value}</dd></div>)}</dl>
    {booking.canAccept || booking.canReject ? <section className="mt-8 rounded border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Decision</h2><p className="mt-2 text-sm text-slate-400">Acceptance records operational approval. Driver and vehicle assignment is a separate confirmed action.</p><label className="mt-5 block text-sm font-medium" htmlFor="reason">Rejection reason</label><textarea id="reason" maxLength={300} value={reason} onChange={e => setReason(e.target.value)} placeholder="Internal reason; the customer sees a safe generic message" className="mt-2 min-h-24 w-full rounded border border-slate-700 bg-slate-950 p-3"/><div className="mt-4 flex gap-3"><button disabled={busy !== null} onClick={() => void transition("accept")} className="rounded bg-emerald-500 px-4 py-2 font-semibold text-slate-950 disabled:opacity-50">{busy === "accept" ? "Accepting…" : "Accept request"}</button><button disabled={busy !== null} onClick={() => void transition("reject")} className="rounded border border-red-700 px-4 py-2 font-semibold text-red-300 disabled:opacity-50">{busy === "reject" ? "Rejecting…" : "Reject request"}</button></div></section> : null}
    {booking.canAssign ? <AssignmentPanel booking={booking} onAssigned={value => { setBooking(value); setNotice("Driver and vehicle assigned."); }} /> : null}
    {booking.status === "driver_assigned" ? <section className="mt-8 rounded border border-emerald-900 bg-emerald-950/30 p-6"><h2 className="text-xl font-semibold">Assignment</h2><p className="mt-3">{booking.assignedDriverName} · {booking.assignedVehicleTypeName} · {booking.assignedVehicleRegistration}</p><p className="mt-2 text-sm text-slate-400">Initial assignment is complete. Reassignment and unassignment are not available in Phase 8.</p></section> : null}
    <section className="mt-8"><h2 className="text-xl font-semibold">Status history</h2><ol className="mt-4 space-y-3">{booking.history.map((entry, index) => <li key={`${entry.createdAt}-${index}`} className="border-l-2 border-sky-500 pl-4"><strong>{entry.statusLabel}</strong><p className="text-sm text-slate-400">{localDateTime(entry.createdAt, "Asia/Kolkata")}{entry.reason ? ` · ${entry.reason}` : ""}</p></li>)}</ol></section></div>;
}
