"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/AuthProvider";
import { problem, type AdminDriverDetails } from "@/lib/admin-bookings";

export function DriverCreate() {
  const auth = useAuth(); const router = useRouter(); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [employment, setEmployment] = useState("active"); const [availability, setAvailability] = useState("available"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await auth.authenticatedFetch("/api/admin/drivers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ displayName: name, phoneNumber: phone, employmentStatus: employment, availabilityStatus: availability }) }); if (!response.ok) throw new Error(await problem(response)); const driver = await response.json() as AdminDriverDetails; router.push(`/drivers/${driver.id}`); } catch (e) { setError(e instanceof Error ? e.message : "Could not create driver."); } finally { setBusy(false); } }
  return <div className="max-w-2xl"><Link href="/drivers" className="text-sm font-semibold text-sky-400">← Drivers</Link><h1 className="mt-5 text-3xl font-semibold">Add Driver</h1><p className="mt-2 text-sm text-slate-400">The immutable driver number and persisted driver role are assigned securely by the API.</p><form onSubmit={submit} className="mt-7 grid gap-5 rounded border border-slate-800 bg-slate-900 p-6"><Field label="Driver name"><input required minLength={2} value={name} onChange={e => setName(e.target.value)} className="input"/></Field><Field label="Mobile number"><input required value={phone} onChange={e => setPhone(e.target.value)} inputMode="tel" className="input"/></Field><Field label="Employment status"><select value={employment} onChange={e => setEmployment(e.target.value)} className="input"><option value="active">Active</option><option value="inactive">Inactive</option><option value="suspended">Suspended</option></select></Field><Field label="Availability"><select value={availability} onChange={e => setAvailability(e.target.value)} className="input"><option value="available">Available</option><option value="unavailable">Unavailable</option><option value="off_duty">Off duty</option><option value="on_trip">On trip</option></select></Field>{error ? <p role="alert" className="text-red-300">{error}</p> : null}<button disabled={busy} className="rounded bg-sky-500 px-4 py-2 font-semibold text-slate-950 disabled:opacity-50">{busy ? "Creating…" : "Create Driver"}</button></form></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-sm font-medium">{label}{children}</label>; }
