"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useAuth } from "@/components/AuthProvider";
import { problem, type AdminDriverDetails, type AdminVehiclePage } from "@/lib/admin-bookings";

export function DriverDetails({ id }: { id: string }) {
  const auth = useAuth(); const [driver, setDriver] = useState<AdminDriverDetails | null>(null); const [initialEmployment, setInitialEmployment] = useState(""); const [vehicles, setVehicles] = useState<AdminVehiclePage | null>(null); const [vehicleId, setVehicleId] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const [d, v] = await Promise.all([auth.authenticatedFetch(`/api/admin/drivers/${id}`), auth.authenticatedFetch("/api/admin/vehicles?eligibleOnly=true&pageSize=100")]); if (!d.ok) throw new Error(await problem(d)); if (!v.ok) throw new Error(await problem(v)); const value = await d.json() as AdminDriverDetails; setDriver(value); setInitialEmployment(value.employmentStatus); setVehicleId(value.currentVehicleId ?? ""); setVehicles(await v.json() as AdminVehiclePage); }, [auth, id]);
  useEffect(() => { void load().catch(e => setError(e instanceof Error ? e.message : "Could not load driver.")); }, [load]);
  async function save(event: FormEvent) { event.preventDefault(); if (!driver) return; if (initialEmployment === "active" && driver.employmentStatus !== "active" && !window.confirm(`Deactivate driver ${driver.driverNumber}?\n\nThis driver will no longer be available for new assignments. Historical information will be preserved.`)) return; await action(`/api/admin/drivers/${id}`, "PUT", { displayName: driver.displayName, phoneNumber: driver.phoneNumber, employmentStatus: driver.employmentStatus, availabilityStatus: driver.availabilityStatus, version: driver.version }, "Driver updated."); }
  async function toggle() { if (!driver) return; const active = driver.employmentStatus === "active"; if (active && !window.confirm(`Deactivate driver ${driver.driverNumber}?\n\nThis driver will no longer be available for new assignments. Historical information will be preserved.`)) return; await action(`/api/admin/drivers/${id}/${active ? "deactivate" : "reactivate"}`, "POST", { version: driver.version }, active ? "Driver deactivated." : "Driver reactivated."); }
  async function tag() { if (!driver) return; await action(`/api/admin/drivers/${id}/vehicle`, "POST", { vehicleId: vehicleId || null, version: driver.version }, vehicleId ? "Vehicle tagged." : "Vehicle tag removed."); }
  async function action(url: string, method: string, body: object, message: string) { setBusy(true); setError(""); setNotice(""); try { const response = await auth.authenticatedFetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(await problem(response)); const value = await response.json() as AdminDriverDetails; setDriver(value); setInitialEmployment(value.employmentStatus); setVehicleId(value.currentVehicleId ?? ""); setNotice(message); } catch (e) { setError(e instanceof Error ? e.message : "Could not update driver."); } finally { setBusy(false); } }
  if (!driver) return error ? <p role="alert" className="text-red-300">{error}</p> : <p role="status" className="text-slate-400">Loading driver…</p>;
  return <div><Link href="/drivers" className="text-sm font-semibold text-sky-400">← Drivers</Link><div className="mt-5"><p className="font-mono text-sm text-sky-300">{driver.driverNumber}</p><h1 className="mt-1 text-3xl font-semibold">{driver.displayName}</h1></div>{notice ? <p role="status" className="mt-5 text-emerald-300">{notice}</p> : null}{error ? <p role="alert" className="mt-5 text-red-300">{error}</p> : null}
    <form onSubmit={save} className="mt-7 grid gap-5 rounded border border-slate-800 bg-slate-900 p-6 sm:grid-cols-2"><label className="grid gap-2 text-sm">Driver number<input readOnly value={driver.driverNumber} className="input opacity-70"/></label><label className="grid gap-2 text-sm">Driver name<input required value={driver.displayName} onChange={e => setDriver({ ...driver, displayName: e.target.value })} className="input"/></label><label className="grid gap-2 text-sm">Mobile number<input required value={driver.phoneNumber} onChange={e => setDriver({ ...driver, phoneNumber: e.target.value })} className="input"/></label><label className="grid gap-2 text-sm">Employment status<select value={driver.employmentStatus} onChange={e => setDriver({ ...driver, employmentStatus: e.target.value })} className="input"><option value="active">Active</option><option value="inactive">Inactive</option><option value="suspended">Suspended</option></select></label><label className="grid gap-2 text-sm">Availability<select value={driver.availabilityStatus} onChange={e => setDriver({ ...driver, availabilityStatus: e.target.value })} className="input"><option value="available">Available</option><option value="unavailable">Unavailable</option><option value="off_duty">Off duty</option><option value="on_trip">On trip</option></select></label><div className="flex items-end gap-3"><button disabled={busy} className="rounded bg-sky-500 px-4 py-2 font-semibold text-slate-950 disabled:opacity-50">Save changes</button><button type="button" disabled={busy} onClick={() => void toggle()} className="rounded border border-amber-700 px-4 py-2 text-amber-300 disabled:opacity-50">{driver.employmentStatus === "active" ? "Deactivate driver" : "Reactivate driver"}</button></div></form>
    <section className="mt-7 rounded border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Tagged vehicle</h2><div className="mt-4 flex flex-col gap-3 sm:flex-row"><select aria-label="Tagged vehicle" value={vehicleId} onChange={e => setVehicleId(e.target.value)} className="input flex-1"><option value="">No tagged vehicle</option>{vehicles?.items.map(v => <option key={v.id} value={v.id}>{v.registrationNumber} · {v.vehicleTypeName}{v.currentDriverId && v.currentDriverId !== driver.id ? ` · currently ${v.currentDriverNumber}` : ""}</option>)}</select><button disabled={busy} onClick={() => void tag()} className="rounded border border-sky-700 px-4 py-2 text-sky-300">Save vehicle tag</button></div></section>
    <section className="mt-7"><h2 className="text-xl font-semibold">Vehicle association history</h2>{driver.vehicleHistory.length === 0 ? <p className="mt-3 text-slate-400">No vehicle associations yet.</p> : <ul className="mt-3 space-y-2">{driver.vehicleHistory.map(x => <li key={x.id} className="rounded border border-slate-800 p-4">{x.vehicleRegistration} · {new Date(x.assignedFrom).toLocaleString("en-IN")} → {x.assignedTo ? new Date(x.assignedTo).toLocaleString("en-IN") : "Current"}</li>)}</ul>}</section>
  </div>;
}
