"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/AuthProvider";
import { problem, type AdminVehicleDetails, type AdminVehicleType } from "@/lib/admin-bookings";

export function VehicleCreate() {
  const auth = useAuth(); const router = useRouter(); const [types, setTypes] = useState<AdminVehicleType[]>([]); const [registration, setRegistration] = useState(""); const [typeId, setTypeId] = useState(""); const [capacity, setCapacity] = useState(4); const [status, setStatus] = useState("active"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void auth.authenticatedFetch("/api/admin/vehicles/types").then(async response => { if (!response.ok) throw new Error(await problem(response)); const values = await response.json() as AdminVehicleType[]; setTypes(values); if (values[0]) { setTypeId(values[0].id); setCapacity(values[0].typicalCapacity); } }).catch(e => setError(e instanceof Error ? e.message : "Could not load vehicle types.")); }, [auth]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await auth.authenticatedFetch("/api/admin/vehicles", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ registrationNumber: registration, vehicleTypeId: typeId, capacity, status }) }); if (!response.ok) throw new Error(await problem(response)); const vehicle = await response.json() as AdminVehicleDetails; router.push(`/vehicles/${vehicle.id}`); } catch (e) { setError(e instanceof Error ? e.message : "Could not create vehicle."); } finally { setBusy(false); } }
  return <div className="max-w-2xl"><Link href="/vehicles" className="text-sm font-semibold text-sky-400">← Vehicles</Link><h1 className="mt-5 text-3xl font-semibold">Add Vehicle</h1><form onSubmit={submit} className="mt-7 grid gap-5 rounded border border-slate-800 bg-slate-900 p-6"><label className="grid gap-2 text-sm">Registration number<input required value={registration} onChange={e => setRegistration(e.target.value)} className="input" placeholder="KA01AB1234"/></label><label className="grid gap-2 text-sm">Vehicle type<select required value={typeId} onChange={e => { setTypeId(e.target.value); const type = types.find(x => x.id === e.target.value); if (type) setCapacity(type.typicalCapacity); }} className="input">{types.map(type => <option key={type.id} value={type.id}>{type.name}</option>)}</select></label><label className="grid gap-2 text-sm">Capacity<input required min={1} max={30} type="number" value={capacity} onChange={e => setCapacity(Number(e.target.value))} className="input"/></label><label className="grid gap-2 text-sm">Operational status<select value={status} onChange={e => setStatus(e.target.value)} className="input"><option value="active">Active</option><option value="inactive">Inactive</option><option value="maintenance">Maintenance</option></select></label>{error ? <p role="alert" className="text-red-300">{error}</p> : null}<button disabled={busy || !typeId} className="rounded bg-sky-500 px-4 py-2 font-semibold text-slate-950 disabled:opacity-50">{busy ? "Creating…" : "Create Vehicle"}</button></form></div>;
}
