"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useAuth } from "@/components/AuthProvider";
import { problem, type AdminDriverPage, type AdminVehicleDetails, type AdminVehicleType } from "@/lib/admin-bookings";

export function VehicleDetails({ id }: { id: string }) {
  const auth = useAuth(); const [vehicle, setVehicle] = useState<AdminVehicleDetails | null>(null); const [initialStatus, setInitialStatus] = useState(""); const [types, setTypes] = useState<AdminVehicleType[]>([]); const [drivers, setDrivers] = useState<AdminDriverPage | null>(null); const [driverId, setDriverId] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const responses = await Promise.all([auth.authenticatedFetch(`/api/admin/vehicles/${id}`), auth.authenticatedFetch("/api/admin/vehicles/types"), auth.authenticatedFetch("/api/admin/drivers?eligibleOnly=true&pageSize=100")]); for (const response of responses) if (!response.ok) throw new Error(await problem(response)); const value = await responses[0].json() as AdminVehicleDetails; setVehicle(value); setInitialStatus(value.status); setDriverId(value.currentDriverId ?? ""); setTypes(await responses[1].json() as AdminVehicleType[]); setDrivers(await responses[2].json() as AdminDriverPage); }, [auth, id]);
  useEffect(() => { void load().catch(e => setError(e instanceof Error ? e.message : "Could not load vehicle.")); }, [load]);
  async function save(event: FormEvent) { event.preventDefault(); if (!vehicle) return; if (initialStatus === "active" && vehicle.status !== "active" && !window.confirm(`Deactivate vehicle ${vehicle.registrationNumber}?\n\nIt will no longer be available for new assignments. Historical information will be preserved.`)) return; await action(`/api/admin/vehicles/${id}`, "PUT", { registrationNumber: vehicle.registrationNumber, vehicleTypeId: vehicle.vehicleTypeId, capacity: vehicle.capacity, status: vehicle.status, version: vehicle.version }, "Vehicle updated."); }
  async function toggle() { if (!vehicle) return; const active = vehicle.status === "active"; if (active && !window.confirm(`Deactivate vehicle ${vehicle.registrationNumber}?\n\nIt will no longer be available for new assignments. Historical information will be preserved.`)) return; await action(`/api/admin/vehicles/${id}/${active ? "deactivate" : "reactivate"}`, "POST", { version: vehicle.version }, active ? "Vehicle deactivated." : "Vehicle reactivated."); }
  async function tag() { if (!vehicle) return; await action(`/api/admin/vehicles/${id}/driver`, "POST", { driverId: driverId || null, version: vehicle.version }, driverId ? "Driver tagged." : "Driver tag removed."); }
  async function action(url: string, method: string, body: object, message: string) { setBusy(true); setError(""); setNotice(""); try { const response = await auth.authenticatedFetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(await problem(response)); const value = await response.json() as AdminVehicleDetails; setVehicle(value); setInitialStatus(value.status); setDriverId(value.currentDriverId ?? ""); setNotice(message); } catch (e) { setError(e instanceof Error ? e.message : "Could not update vehicle."); } finally { setBusy(false); } }
  if (!vehicle) return error ? <p role="alert" className="text-red-300">{error}</p> : <p role="status" className="text-slate-400">Loading vehicle…</p>;
  return <div><Link href="/vehicles" className="text-sm font-semibold text-sky-400">← Vehicles</Link><h1 className="mt-5 font-mono text-3xl font-semibold">{vehicle.registrationNumber}</h1>{notice ? <p role="status" className="mt-5 text-emerald-300">{notice}</p> : null}{error ? <p role="alert" className="mt-5 text-red-300">{error}</p> : null}
    <form onSubmit={save} className="mt-7 grid gap-5 rounded border border-slate-800 bg-slate-900 p-6 sm:grid-cols-2"><label className="grid gap-2 text-sm">Registration number<input required value={vehicle.registrationNumber} onChange={e => setVehicle({ ...vehicle, registrationNumber: e.target.value })} className="input"/></label><label className="grid gap-2 text-sm">Vehicle type<select value={vehicle.vehicleTypeId} onChange={e => setVehicle({ ...vehicle, vehicleTypeId: e.target.value })} className="input">{types.map(type => <option key={type.id} value={type.id}>{type.name}</option>)}</select></label><label className="grid gap-2 text-sm">Capacity<input type="number" min={1} max={30} value={vehicle.capacity} onChange={e => setVehicle({ ...vehicle, capacity: Number(e.target.value) })} className="input"/></label><label className="grid gap-2 text-sm">Operational status<select value={vehicle.status} onChange={e => setVehicle({ ...vehicle, status: e.target.value })} className="input"><option value="active">Active</option><option value="inactive">Inactive</option><option value="maintenance">Maintenance</option></select></label><div className="flex items-end gap-3 sm:col-span-2"><button disabled={busy} className="rounded bg-sky-500 px-4 py-2 font-semibold text-slate-950 disabled:opacity-50">Save changes</button><button type="button" disabled={busy} onClick={() => void toggle()} className="rounded border border-amber-700 px-4 py-2 text-amber-300 disabled:opacity-50">{vehicle.status === "active" ? "Deactivate vehicle" : "Reactivate vehicle"}</button></div></form>
    <section className="mt-7 rounded border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Tagged driver</h2><div className="mt-4 flex flex-col gap-3 sm:flex-row"><select aria-label="Tagged driver" value={driverId} onChange={e => setDriverId(e.target.value)} className="input flex-1"><option value="">No tagged driver</option>{drivers?.items.map(d => <option key={d.id} value={d.id}>{d.driverNumber} — {d.displayName}{d.currentVehicleId && d.currentVehicleId !== vehicle.id ? ` · currently ${d.currentVehicleRegistration}` : ""}</option>)}</select><button disabled={busy} onClick={() => void tag()} className="rounded border border-sky-700 px-4 py-2 text-sky-300">Save driver tag</button></div></section>
    <section className="mt-7"><h2 className="text-xl font-semibold">Driver association history</h2>{vehicle.driverHistory.length === 0 ? <p className="mt-3 text-slate-400">No driver associations yet.</p> : <ul className="mt-3 space-y-2">{vehicle.driverHistory.map(x => <li key={x.id} className="rounded border border-slate-800 p-4">{x.driverNumber} — {x.driverName} · {new Date(x.assignedFrom).toLocaleString("en-IN")} → {x.assignedTo ? new Date(x.assignedTo).toLocaleString("en-IN") : "Current"}</li>)}</ul>}</section>
  </div>;
}
