"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useAuth } from "@/components/AuthProvider";
import { problem, type AdminVehiclePage } from "@/lib/admin-bookings";

export function VehicleList() {
  const auth = useAuth(); const [data, setData] = useState<AdminVehiclePage | null>(null); const [search, setSearch] = useState(""); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [error, setError] = useState("");
  const load = useCallback(async () => { setError(""); const response = await auth.authenticatedFetch(`/api/admin/vehicles?page=${page}&pageSize=25&search=${encodeURIComponent(query)}`); if (!response.ok) throw new Error(await problem(response)); setData(await response.json() as AdminVehiclePage); }, [auth, page, query]);
  useEffect(() => { void load().catch(e => setError(e instanceof Error ? e.message : "Could not load vehicles.")); }, [load]);
  function submit(event: FormEvent) { event.preventDefault(); setPage(1); setQuery(search.trim()); }
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-sky-400">Fleet</p><h1 className="mt-2 text-3xl font-semibold">Vehicles</h1></div><Link href="/vehicles/new" className="rounded bg-sky-500 px-4 py-2 font-semibold text-slate-950">+ Add Vehicle</Link></div><form onSubmit={submit} className="mt-6 flex max-w-xl gap-2"><label className="sr-only" htmlFor="vehicle-search">Search vehicles</label><input id="vehicle-search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Registration number" className="input min-w-0 flex-1"/><button className="rounded border border-slate-700 px-4 py-2">Search</button></form>
    {error ? <p role="alert" className="mt-6 text-red-300">{error}</p> : !data ? <p role="status" className="mt-6 text-slate-400">Loading vehicles…</p> : data.items.length === 0 ? <p className="mt-6 rounded border border-slate-800 bg-slate-900 p-6 text-slate-400">No vehicles found. Add the first vehicle to begin fleet operations.</p> : <div className="mt-6 overflow-x-auto rounded border border-slate-800"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-900 text-slate-400"><tr>{["Registration","Vehicle Type","Status","Current Driver","Actions"].map(x => <th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{data.items.map(vehicle => <tr key={vehicle.id} className="border-t border-slate-800"><td className="px-4 py-3 font-mono text-sky-300">{vehicle.registrationNumber}</td><td className="px-4 py-3">{vehicle.vehicleTypeName}</td><td className="px-4 py-3 capitalize">{vehicle.status}</td><td className="px-4 py-3">{vehicle.currentDriverNumber ? `${vehicle.currentDriverNumber} — ${vehicle.currentDriverName}` : "—"}</td><td className="px-4 py-3"><Link href={`/vehicles/${vehicle.id}`} className="font-medium text-sky-400">View / Edit</Link></td></tr>)}</tbody></table></div>}
    {data ? <div className="mt-5 flex items-center gap-3"><button disabled={page <= 1} onClick={() => setPage(x => x - 1)} className="rounded border border-slate-700 px-3 py-2 disabled:opacity-40">Previous</button><span className="text-sm text-slate-400">Page {data.page} of {Math.max(1, data.totalPages)}</span><button disabled={page >= data.totalPages} onClick={() => setPage(x => x + 1)} className="rounded border border-slate-700 px-3 py-2 disabled:opacity-40">Next</button></div> : null}
  </div>;
}
