import type { LocationPageContent, RoutePageContent } from "@/content/seo/types";

export const unpublishedDemoRoute: RoutePageContent = {
  slug: "unpublished-demo-route",
  published: false,
  indexable: false,
  lastUpdated: "2026-08-26",
  originId: "whitefield",
  destinationId: "blr-airport",
  routeType: "airport",
  direction: "to-airport",
  seoTitle: "Unpublished demo",
  metaDescription: "Must never appear in the sitemap or as a public page.",
  h1: "Unpublished demo",
  heroEyebrow: "Draft",
  heroText: "Draft",
  heroImage: { src: "/images/hero-airport.jpg", alt: "Draft fixture" },
  primaryCtaLabel: "Book",
  bookingHeading: "Book",
  bookingSubmitLabel: "Book",
  defaultTripType: "airport",
  summary: {
    from: "Whitefield",
    to: "Bangalore Airport",
    tripType: "Draft",
    vehicleCategories: "Sedan",
    distanceNote: "Hidden",
    durationNote: "Approximate information — final journey time depends on traffic.",
  },
  intro: "Draft",
  pickupInformation: { heading: "Pickup", body: "Draft" },
  destinationInformation: { heading: "Drop", body: "Draft" },
  travelGuidance: { heading: "Guidance", body: "Draft" },
  whyChoose: [],
  howBookingWorks: [],
  vehicleNotes: [],
  relatedSlugs: [],
  parentServiceId: "airport-taxi-bangalore",
  faq: [],
  farePlaceholder: "Price on request",
};

/** Published for internal review, never sitemap / Google index. */
export const reviewOnlyDemoRoute: RoutePageContent = {
  slug: "review-only-demo-route",
  published: true,
  indexable: false,
  lastUpdated: "2026-08-26",
  originId: "hsr-layout",
  destinationId: "blr-airport",
  routeType: "airport",
  direction: "to-airport",
  seoTitle: "Review-only HSR Layout airport drop",
  metaDescription: "Internal review fixture. Not for search indexing.",
  h1: "Review-only HSR Layout to airport taxi",
  heroEyebrow: "Internal review",
  heroText: "This URL exists so published and indexable can be tested separately. It is not a customer lander.",
  heroImage: { src: "/images/hero-airport.jpg", alt: "Review fixture" },
  primaryCtaLabel: "Book this route",
  bookingHeading: "Review fixture",
  bookingSubmitLabel: "Request",
  defaultTripType: "airport",
  summary: {
    from: "HSR Layout",
    to: "Bangalore Airport",
    tripType: "Airport drop",
    vehicleCategories: "Sedan",
    distanceNote: "Exact kilometres will appear when mapping is connected.",
    durationNote: "Approximate information — final journey time depends on traffic.",
  },
  intro: "Fixture page for noindex behaviour. Not a production marketing URL.",
  pickupInformation: { heading: "Pickup", body: "Review fixture." },
  destinationInformation: { heading: "Drop", body: "Review fixture." },
  travelGuidance: { heading: "Guidance", body: "Review fixture." },
  whyChoose: [{ title: "Fixture", body: "Used in tests only." }],
  howBookingWorks: [{ title: "Fixture", body: "Not a live booking path." }],
  vehicleNotes: [{ category: "Sedan", note: "Fixture." }],
  relatedSlugs: ["whitefield-to-bangalore-airport-taxi"],
  parentServiceId: "airport-taxi-bangalore",
  faq: [{ question: "Is this indexed?", answer: "No. It is published for review and marked noindex." }],
  farePlaceholder: "Price on request",
};

export const locationPages: readonly LocationPageContent[] = [];
