import type { LocationContent } from "@/content/seo/types";

function locality(id: string, name: string): LocationContent {
  return {
    id,
    name,
    slug: id,
    type: "locality",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    published: true,
  };
}

function outstation(id: string, name: string, alternateName?: string): LocationContent {
  return {
    id,
    name,
    slug: id,
    alternateName,
    type: "outstation",
    city: name,
    state: "Karnataka",
    country: "India",
    published: true,
  };
}

/** Location records for route composition. They do not create SEO URLs by themselves. */
export const locations: readonly LocationContent[] = [
  {
    id: "bangalore",
    name: "Bangalore",
    slug: "bangalore",
    alternateName: "Bengaluru",
    type: "city",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    published: true,
  },
  {
    id: "blr-airport",
    name: "Bangalore Airport",
    slug: "bangalore-airport",
    alternateName: "Kempegowda International Airport",
    type: "airport",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    airportCode: "BLR",
    published: true,
  },
  locality("whitefield", "Whitefield"),
  locality("electronic-city", "Electronic City"),
  locality("koramangala", "Koramangala"),
  locality("hsr-layout", "HSR Layout"),
  locality("marathahalli", "Marathahalli"),
  locality("indiranagar", "Indiranagar"),
  locality("jayanagar", "Jayanagar"),
  locality("jp-nagar", "JP Nagar"),
  locality("hebbal", "Hebbal"),
  locality("yelahanka", "Yelahanka"),
  locality("bellandur", "Bellandur"),
  locality("sarjapur-road", "Sarjapur Road"),
  locality("btm-layout", "BTM Layout"),
  locality("banashankari", "Banashankari"),
  locality("rajajinagar", "Rajajinagar"),
  locality("malleshwaram", "Malleshwaram"),
  locality("kr-puram", "KR Puram"),
  locality("mahadevapura", "Mahadevapura"),
  locality("manyata-tech-park", "Manyata Tech Park"),
  locality("devanahalli", "Devanahalli"),
  outstation("mysore", "Mysore", "Mysuru"),
  outstation("coorg", "Coorg", "Kodagu"),
  {
    id: "ooty",
    name: "Ooty",
    slug: "ooty",
    alternateName: "Udhagamandalam",
    type: "outstation",
    city: "Ooty",
    state: "Tamil Nadu",
    country: "India",
    published: true,
  },
  {
    id: "chennai",
    name: "Chennai",
    slug: "chennai",
    type: "outstation",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    published: true,
  },
  outstation("chikmagalur", "Chikmagalur"),
  {
    id: "tirupati",
    name: "Tirupati",
    slug: "tirupati",
    type: "outstation",
    city: "Tirupati",
    state: "Andhra Pradesh",
    country: "India",
    published: true,
  },
];
