export type AdminBookingListItem = { id: string; bookingNumber: string; status: string; statusLabel: string; pickup: string; drop: string; pickupAt: string; pickupTimezone: string; pickupLocalDate: string; vehicleType: string; vehicleTypeName: string; createdAt: string };
export type AdminBookingPage = { items: AdminBookingListItem[]; page: number; pageSize: number; totalCount: number; totalPages: number };
export type AdminBookingHistory = { fromStatus?: string | null; status: string; statusLabel: string; createdAt: string; reason?: string | null };
export type AdminBookingDetails = AdminBookingListItem & { serviceType: string; airportJourneyType?: string | null; returnAt?: string | null; returnLocalDate?: string | null; contactName: string; contactMobile: string; contactEmail?: string | null; customerNotes?: string | null; canAccept: boolean; canReject: boolean; canAssign: boolean; assignedDriverName?: string | null; assignedVehicleRegistration?: string | null; assignedVehicleTypeName?: string | null; history: AdminBookingHistory[] };
export type AdminDriver = { id: string; driverNumber: string; displayName: string; phoneNumber: string; employmentStatus: string; availabilityStatus: string; eligible: boolean; currentVehicleId?: string | null; currentVehicleRegistration?: string | null };
export type AdminVehicle = { id: string; registrationNumber: string; vehicleTypeId?: string; vehicleType: string; vehicleTypeName: string; capacity: number; status: string; eligible: boolean; currentDriverId?: string | null; currentDriverNumber?: string | null; currentDriverName?: string | null };
export type AdminDriverPage = { items: AdminDriver[]; page: number; pageSize: number; totalCount: number; totalPages: number };
export type AdminVehiclePage = { items: AdminVehicle[]; page: number; pageSize: number; totalCount: number; totalPages: number };
export type AdminRosterHistory = { id: string; driverId: string; driverNumber: string; driverName: string; vehicleId: string; vehicleRegistration: string; assignedFrom: string; assignedTo?: string | null };
export type AdminDriverDetails = AdminDriver & { version: number; vehicleHistory: AdminRosterHistory[] };
export type AdminVehicleDetails = AdminVehicle & { vehicleTypeId: string; version: number; driverHistory: AdminRosterHistory[] };
export type AdminVehicleType = { id: string; code: string; name: string; typicalCapacity: number };
export async function problem(response: Response) { try { const body = await response.json() as { detail?: string; title?: string }; return body.detail ?? body.title ?? "The request failed."; } catch { return "The request failed."; } }
export function localDateTime(value: string, timezone: string) { return new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: timezone }).format(new Date(value)); }
