import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { AdminGuard } from "@/components/AdminGuard";
import { BookingQueue } from "@/components/BookingQueue";
import { BookingDetails } from "@/components/BookingDetails";
import { AdminLogin } from "@/components/AdminLogin";

const replace = vi.fn(); const authenticatedFetch = vi.fn(); const requestOtp = vi.fn(); const peekDevOtp = vi.fn(); const verifyOtp = vi.fn(); const logout = vi.fn();
const auth: { ready: boolean; user: null | { userId: string; phoneNumber: string; maskedPhone: string; roles: string[] }; authenticatedFetch: typeof authenticatedFetch; requestOtp: typeof requestOtp; peekDevOtp: typeof peekDevOtp; verifyOtp: typeof verifyOtp; logout: typeof logout } = { ready: true, user: { userId: "a", phoneNumber: "+919876543210", maskedPhone: "******3210", roles: ["admin"] }, authenticatedFetch, requestOtp, peekDevOtp, verifyOtp, logout };
vi.mock("next/navigation", () => ({ useRouter: () => ({ replace }) }));
vi.mock("@/components/AuthProvider", () => ({ useAuth: () => auth }));
const item = { id: "11111111-1111-4111-8111-111111111111", bookingNumber: "BLR-2026-000001", status: "pending", statusLabel: "Pending confirmation", pickup: "MG Road", drop: "Kempegowda International Airport (BLR)", pickupAt: "2026-09-10T04:30:00Z", pickupTimezone: "Asia/Kolkata", pickupLocalDate: "2026-09-10", vehicleType: "sedan", vehicleTypeName: "Sedan", createdAt: "2026-08-27T10:00:00Z" };
const details = { ...item, serviceType: "airport", airportJourneyType: "drop", contactName: "Customer", contactMobile: "+919876543210", canAccept: true, canReject: true, history: [{ status: "pending", statusLabel: "Pending confirmation", createdAt: item.createdAt, reason: "Booking request received" }] };

describe("admin operations frontend", () => {
  beforeEach(() => { authenticatedFetch.mockReset(); requestOtp.mockReset(); peekDevOtp.mockReset(); verifyOtp.mockReset(); logout.mockReset(); replace.mockReset(); vi.restoreAllMocks(); auth.ready = true; auth.user = { userId: "a", phoneNumber: "+919876543210", maskedPhone: "******3210", roles: ["admin"] }; });
  it("redirects signed-out users and denies non-admin accounts", () => { auth.user = null; const first = render(<AdminGuard><p>Queue</p></AdminGuard>); expect(replace).toHaveBeenCalledWith("/login"); first.unmount(); auth.user = { userId: "c", phoneNumber: "+919876543210", maskedPhone: "******3210", roles: ["customer"] }; render(<AdminGuard><p>Queue</p></AdminGuard>); expect(screen.getByRole("alert")).toHaveTextContent("Access denied"); });
  it("shows pending queue, filters, empty and error states", async () => { authenticatedFetch.mockResolvedValueOnce(new Response(JSON.stringify({ items: [item], page: 1, pageSize: 25, totalCount: 1, totalPages: 1 }))); const user = userEvent.setup(); render(<BookingQueue />); expect(await screen.findByText(item.bookingNumber)).toBeInTheDocument(); authenticatedFetch.mockResolvedValueOnce(new Response(JSON.stringify({ items: [], page: 1, pageSize: 25, totalCount: 0, totalPages: 0 }))); await user.click(screen.getByRole("button", { name: "rejected" })); expect(await screen.findByText(/no rejected bookings/i)).toBeInTheDocument(); authenticatedFetch.mockResolvedValueOnce(new Response(JSON.stringify({ detail: "Unavailable" }), { status: 503 })); await user.click(screen.getByRole("button", { name: "accepted" })); expect(await screen.findByRole("alert")).toHaveTextContent("Unavailable"); });
  it("confirms accept, disables both actions in flight, and refreshes state", async () => { let resolve!: (response: Response) => void; authenticatedFetch.mockResolvedValueOnce(new Response(JSON.stringify(details))).mockReturnValueOnce(new Promise<Response>(done => { resolve = done; })); vi.spyOn(window, "confirm").mockReturnValue(true); const user = userEvent.setup(); render(<BookingDetails id={item.id} />); await screen.findByText(item.bookingNumber); await user.click(screen.getByRole("button", { name: /accept request/i })); expect(screen.getByRole("button", { name: /accepting/i })).toBeDisabled(); expect(screen.getByRole("button", { name: /reject request/i })).toBeDisabled(); resolve(new Response(JSON.stringify({ ...details, status: "accepted", statusLabel: "Accepted — awaiting assignment", canAccept: false, canReject: false }))); expect(await screen.findByText("Booking request accepted.")).toBeInTheDocument(); });
  it("validates rejection and explains a competing transition", async () => { authenticatedFetch.mockResolvedValueOnce(new Response(JSON.stringify(details))); vi.spyOn(window, "confirm").mockReturnValue(true); const user = userEvent.setup(); render(<BookingDetails id={item.id} />); await screen.findByText(item.bookingNumber); await user.click(screen.getByRole("button", { name: /reject request/i })); expect(screen.getByRole("alert")).toHaveTextContent(/at least 3/i); await user.type(screen.getByLabelText(/rejection reason/i), "No capacity"); authenticatedFetch.mockResolvedValueOnce(new Response(null, { status: 409 })); await user.click(screen.getByRole("button", { name: /reject request/i })); expect(await screen.findByRole("alert")).toHaveTextContent(/changed.*refresh/i); });
  it("shows the development OTP and verifies the real entered code", async () => { auth.user = null; requestOtp.mockResolvedValue(undefined); peekDevOtp.mockResolvedValue("123456"); verifyOtp.mockResolvedValue(undefined); const user = userEvent.setup(); render(<AdminLogin />); await user.type(screen.getByLabelText(/mobile number/i), "9876543210"); await user.click(screen.getByRole("button", { name: /send otp/i })); expect(await screen.findByText(/development code:/i)).toHaveTextContent("123456"); await user.type(screen.getByLabelText(/one-time code/i), "123456"); await user.click(screen.getByRole("button", { name: /verify otp/i })); expect(verifyOtp).toHaveBeenCalledWith("9876543210", "123456"); });
});
